#ifndef LOC_ENUMS_H
#define LOC_ENUMS_H

enum LocId
{
    //common
    lbathroom,
    lbeach,
    licerink,
    lcinema,
    lgamehall,
    lmetro,
    lbandahome,
    lbandasklad,
    ltailor,
    ltaxi,
    lzoo,
    lpark,
    lshop,
    //gadukino
    lbackwater,
    lgadbana,
    lgadbeach,
    lgaddvor,
    lgadfield,
    lgadforest,
    lgadforestswamp,
    lgadgarden,
    lgadhouse,
    lgadmarket,
    lgadriver,
    lgadroad,
    lgadsarai,
    lgadukino,
    lmeadow,
    lmirahome,
    lswamp,
    lswamphouse,
    lswampspring,
    lswampyard,
    //road, dacha
    ldachi,
    lroad,
    //pavlovo
    lmeyhome,
    lbedrpar,
    lbedrpar2,
    lkorrpar,
    lkuhrpar,
    lsitrpar,
    lbarbershop,
    lcafeparco,
    lcarwash,
    ldancegev,
    lgargazel,
    lgdk,
    lgdkbibl,
    lgdkin,
    lgdkintoilet,
    lgdkkru,
    lgdksport,
    lghomeyard,
    lgkafe,
    lglake,
    lglakenude,
    lglakenudeforest,
    lgorodok,
    lgpoli,
    lgrinok,
    lgschool,
    lgschooltoilet,
    lgshveyfab,
    lhotel,
    ligorhome,
    ljuliamilhome,
    lkotovdom,
    llariskahome,
    lmishahome,
    lnatbelhome,
    lpodezd,
    lshulgaroom,
    lshulgahome,
    lvokzalg,
    lvokzalgin,
    lvolley,
    lalbinaev,
    ldimagohome2,
    //empty loc
    l_work,     //father locs
    l_null,     //father locs
    lreks_home, // sis locs
    lroma_home, // sis locs
    lRoom, //???
    lKitchen, //???
    //city
    lcasino,
    lcasino2,
    //city north
    lautosalonf,
    lautoservicef,
    lautotraidf,
    lbuklinik,
    ldk,
    lkazinosvid,
    llakecafe,
    llaketoilet,
    llogist,
    lnorth,
    lpirsingsalon,
    lskk,
    lskkelevator,
    lskkgym,
    lskkblockzona,
    lskkgymcabtrener,
    lskkgymcardiozona,
    lskkgymfreezona,
    lskkgymgirl,
    lskkgymkor,
    lskkgymleverzona,
    lskkgymmassage,
    lskkgymmedic,
    lskkgymzal,
    lterminal,
    lterminaloffice,
    ltruckparking,
    lvokzal,
    //city center
    lagentned,
    lbank,
    lbordel,
    lbordelgo,
    lbouling,
    lburger,
    lbutik,
    lcenter,
    lclub,
    lfitgirl,
    lfitness,
    lfoto,
    lkamerakpz,
    lkiskis,
    loffice,
    lpornstudio,
    lrestoran,
    lsalon,
    lsexshop,
    lstripclub,
    ltanyaapartment,
    lvipclub,
    //city center university
    luniversity,
    lunicampus,
    lunidorm,
    //city south
    lapteka,
    lbdsm,
    lbdsmclub,
    lbilliard,
    ldanceclass,
    lfrontdoor,
    lhomeyard,
    lkafe,
    lkatspalnya,
    llake,
    lnudelake,
    lpizza,
    lpoli,
    lsouth,
    lsouthmarket,
    lsouthoffice,
    ltrashplace,
    lschoolboy,
    //city south apart
    lbalkon,
    lbedr,
    lkorr,
    lkuhr,
    lsitr,
    lstwork
};

#endif // LOC_ENUMS_H
